### ISSUE TITLE
Bug: Result::unwrap() panic durin gaccount.sync().execute()

### ISSUE THREAD

**Issue by oskyk** [iotaledger/wallet.rs#474] opened 2021-03-30 08:50 UTC
## Bug description

After funding the account `account.sync().execute()` results in
```
/home/oskar/PycharmProjects/iota-chrysalis-provider/venv/bin/python panic.py
[{'address': {'inner': 'atoi1qr8xuhzuj72rpuluatmnaacypgn23yntj3jkyeq3mzzk75sd9g0lvt2nqdu'}, 'balance': 10000000, 'key_index': 0, 'internal': False, 'outputs': {'20143943059dfaf10899648aae7de71c53be68ab877efbee1a87e8c3e8e0dc5d0100': {'transaction_id': '20143943059dfaf10899648aae7de71c53be68ab877efbee1a87e8c3e8e0dc5d', 'message_id': '0b1b9b0b0ba523d773fed14995f93e2966d126bf3cdd06213db8166445a81c47', 'index': 1, 'amount': 10000000, 'is_spent': False, 'address': {'inner': 'atoi1qr8xuhzuj72rpuluatmnaacypgn23yntj3jkyeq3mzzk75sd9g0lvt2nqdu'}}}}, {'address': {'inner': 'atoi1qpe3jyhs6lpk7vy3wwrne6aht02j4ewnme8s89v6d9l5mafs5j3tkjnzhxh'}, 'balance': 0, 'key_index': 1, 'internal': False, 'outputs': {}}]
thread 'pool-thread-#10' panicked at 'called `Result::unwrap()` on an `Err` value: ReturnControlRequest(SLIP10Derive(Ok([53, 221, 119, 232, 69, 90, 155, 63, 169, 91, 17, 156, 229, 188, 138, 147, 121, 196, 173, 224, 248, 136, 166, 100, 108, 163, 236, 46, 82, 176, 140, 7])))', /home/runner/.cargo/git/checkouts/stronghold.rs-fe28308a6634692d/b8904ff/utils/src/ask.rs:48:42
stack backtrace:
```

## Version

https://github.com/iotaledger/wallet.rs/commit/7dac8876bf7ad4531f9afdc5c7d5182a3e95e438

Python Bininding

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 18
- RAM: 8Gb
- Cores: 4
- Device: Lenovo Thinkpad

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Create account:
```import iota_wallet

client_options = {
    'node': 'https://api.lb-0.testnet.chrysalis2.com',
    'local_pow': True
}

acc = iota_wallet.AccountManager(storage_path='iotadb')
acc.set_stronghold_password("yolo")
acc.store_mnemonic("Stronghold")
newacc = acc.create_account(client_options)
newacc.alias("hot")
newacc.initialise()
```
2. Fund account with https://faucet.tanglekit.de/
3. Try to sync:
```import iota_wallet

acc = iota_wallet.AccountManager(storage_path='iotadb')
acc.set_stronghold_password("yolo")
acc.store_mnemonic("Stronghold")
myacc = acc.get_account("hot")
myacc.sync().execute()
print(myacc.addresses())
```
Error is shown on `myacc.sync().execute()`

## Expected behaviour
No error happening on synced account

**Comment by tensor-programming** [comment] 2021-03-30 16:47
Will look into it.  Seems to be a threading problem perhaps as a result of the python runtime.

**Comment by bingyanglin** [comment] 2021-03-31 08:46
@tensor-programming the following Rust codes can reproduce the same error, so there might be a potential issue in Stronghold if the steps to use `wallet.rs` are correct.
1. Run the following codes
```rust
// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use iota_wallet::{
    account_manager::AccountManager, client::ClientOptionsBuilder, message::Transfer, signing::SignerType,
};
use std::num::NonZeroU64;

#[tokio::main]
async fn main() -> iota_wallet::Result<()> {
    let mut manager = AccountManager::builder().finish().await.unwrap();
    manager.set_stronghold_password("password").await.unwrap();
    manager.store_mnemonic(SignerType::Stronghold, None).await.unwrap();

    // first we'll create an example account and store it
    let client_options = ClientOptionsBuilder::new()
        .with_node("https://api.lb-0.testnet.chrysalis2.com")?
        .build()
        .unwrap();
    let account = manager
        .create_account(client_options)?
        .alias("alias")
        .initialise()
        .await?;

    let address = account.generate_address().await?;
    let _ = account.set_alias("Alice").await;
    println!(
        "Send iotas from the faucet to {} and press enter after the transaction got confirmed",
        address.address().to_bech32()
    );

    let mut message = String::new();
    std::io::stdin().read_line(&mut message).unwrap();
    println!("Sending transfer...");
    let message = account
        .transfer(
            Transfer::builder(
                account.latest_address().await.address().clone(),
                NonZeroU64::new(1500000).unwrap(),
            )
            .finish(),
        )
        .await?;

    println!("Message sent: {}", message.id());

    Ok(())
}

```
2. Fund account with https://faucet.tanglekit.de/
3. Get account and then sync again with the following codes
```rust
// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use iota_wallet::{account_manager::AccountManager, signing::SignerType};

#[tokio::main]
async fn main() -> iota_wallet::Result<()> {
    let mut manager = AccountManager::builder().finish().await.unwrap();
    manager.set_stronghold_password("password").await.unwrap();
    manager.store_mnemonic(SignerType::Stronghold, None).await.unwrap();

    let account = manager.get_account("Alice").await?;
    let _ = account.sync().await.execute();

    // get unspent addresses
    let _ = account.list_unspent_addresses();

    // get spent addresses
    let _ = account.list_spent_addresses();

    // get all addresses
    let _ = account.addresses();

    // generate a new unused address
    let _ = account.generate_address().await?;

    Ok(())
}

```
Error messages follow:
```s
thread 'pool-thread-#10' panicked at 'called `Result::unwrap()` on an `Err` value: ReturnControlRequest(SLIP10Derive(Ok([227, 115, 133, 254, 235, 24, 153, 224, 184, 227, 129, 114, 33, 219, 18, 87, 132, 165, 129, 136, 80, 122, 202, 230, 99, 250, 107, 138, 5, 213, 109, 246])))', /home/bylin/.cargo/git/checkouts/stronghold.rs-fe28308a6634692d/b8904ff/utils/src/ask.rs:48:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Note that to reproduce the error, codes in Step 1 and Step 3 need to be executed in separate.

**Comment by laumair** [comment] 2021-06-10 12:02
@bingyanglin @tensor-programming Not sure if this is still an issue?

**Comment by bingyanglin** [comment] 2021-06-10 12:35
@laumair I think we can close it now. I cannot reproduce this error by using the latest commit version [1a2872e](https://github.com/iotaledger/wallet.rs/commit/1a2872e624f4ef20eff0a0dacf497128f139a259).

**Comment by laumair** [comment] 2021-06-10 12:38
@oskyk Please reopen if you have face this again.

**Closed as completed by laumair** 2021-06-10 12:38 UTC
